### ISSUE TITLE
Token.js error on line 130

### ISSUE THREAD

**Issue by Azhrei** [Darinth/maptool.js#1]
It looks like line 130 is wrong.  It's calling setX() and should probably be setNotes(), but you don't seem to have that method.  Just FYI from browsing the code...

**Comment by Darinth** [comment]
Should be resolved :)

**Comment by Azhrei** [comment]
But still no `setNotes()` function?  Or did I just miss it...?

**Comment by Darinth** [comment]
It looks like there's a misunderstanding here. There aren't setThing functions for anything. This library is a wrapper (and functionality extender) around the MapTool token object. So setNotes is on that object, as are most of the getter/setters. In a few cases, there aren't getter/setting functions on the MapTool token object, so I'm using evalMacro to call the necessary MTScript functions to get the data.

**Comment by Darinth** [comment]
I just realized there are 'getters' that actually retrieve the tokens, but those aren't getters in the traditional sense. They're basically constructors that get the MapTool token object and then pass it on to the wrapping function.

**Comment by Azhrei** [comment]
Ah, gotcha.  I misunderstood the use of `this.maptoolToken`; I see now that it's a cache of the value that comes back from MapTool for the actual token object.  Thanks for clarifying.
